IM: Math Utilities
Math Utilities
[Utilities]
Functions
int imRound (float x)
int imResampleInt (int x, float factor)
template<class T , class TU >
T imZeroOrderDecimation (int width, int height, T *map, float xl, float yl, float box_width, float box_height, TU Dummy)
template<class T , class TU >
T imBilinearDecimation (int width, int height, T *map, float xl, float yl, float box_width, float box_height, TU Dummy)
template<class T >
T imZeroOrderInterpolation (int width, int height, T *map, float xl, float yl)
template<class T >
T imBilinearInterpolation (int width, int height, T *map, float xl, float yl)
template<class T , class TU >
T imBicubicInterpolation (int width, int height, T *map, float xl, float yl, TU Dummy)
template<class T >
void imMinMax (const T *map, int count, T &min, T &max, int abssolute=0)
template<class T >
void imMinMaxType (const T *map, int count, T &min, T &max, int abssolute=0)
Detailed Description
When converting between continuous and discrete use:
Continuous = Discrete + 0.5 [Reconstruction/Interpolation]
Discrete = Round(Continuous - 0.5) [Sampling/Quantization]
Notice that must check min-max limits when converting from Continuous to Discrete.
When converting between discrete and discrete use:
integer src_size, dst_len, src_i, dst_i
real factor = (real)(dst_size)/(real)(src_size)
dst_i = Round(factor*(src_i + 0.5) - 0.5)
See im_math.h
Function Documentation
int imRound (float x) [inline]
Round a real to the nearest integer.
Referenced by imColorQuantize(), and imZeroOrderInterpolation().
{
  return (int)(x < 0? x-0.5f: x+0.5f);
}
int imResampleInt (int x, float factor) [inline]
Converts between two discrete grids. factor is "dst_size/src_size".
{
  float xr = factor*(x + 0.5f) - 0.5f;
  return (int)(xr < 0? xr-0.5f: xr+0.5f);  /* Round */
}
template<class T , class TU > T imZeroOrderDecimation (int width, int height, T * map, float xl, float yl, float box_width, float box_height, TU Dummy) [inline]
Does Zero Order Decimation (Mean).
{
  int x0,x1,y0,y1;
  (void)Dummy;
  x0 = (int)floor(xl - box_width/2.0 - 0.5) + 1;
  y0 = (int)floor(yl - box_height/2.0 - 0.5) + 1;
  x1 = (int)floor(xl + box_width/2.0 - 0.5);
  y1 = (int)floor(yl + box_height/2.0 - 0.5);
  if (x0 == x1) x1++;
  if (y0 == y1) y1++;
  x0 = x0<0? 0: x0>width-1? width-1: x0;
  y0 = y0<0? 0: y0>height-1? height-1: y0;
  x1 = x1<0? 0: x1>width-1? width-1: x1;
  y1 = y1<0? 0: y1>height-1? height-1: y1;
  TU Value;
  int Count = 0;
  Value = 0;
  for (int y = y0; y <= y1; y++)
  {
    for (int x = x0; x <= x1; x++)
    {
      Value += map[y*width+x];
      Count++;
    }
  }
  if (Count == 0)
  {
    Value = 0;
    return (T)Value;
  }
  return (T)(Value/(float)Count);
}
template<class T , class TU > T imBilinearDecimation (int width, int height, T * map, float xl, float yl, float box_width, float box_height, TU Dummy) [inline]
Does Bilinear Decimation.
{
  int x0,x1,y0,y1;
  (void)Dummy;
  x0 = (int)floor(xl - box_width/2.0 - 0.5) + 1;
  y0 = (int)floor(yl - box_height/2.0 - 0.5) + 1;
  x1 = (int)floor(xl + box_width/2.0 - 0.5);
  y1 = (int)floor(yl + box_height/2.0 - 0.5);
  if (x0 == x1) x1++;
  if (y0 == y1) y1++;
  x0 = x0<0? 0: x0>width-1? width-1: x0;
  y0 = y0<0? 0: y0>height-1? height-1: y0;
  x1 = x1<0? 0: x1>width-1? width-1: x1;
  y1 = y1<0? 0: y1>height-1? height-1: y1;
  TU Value, LineValue;
  float LineNorm, Norm, dxr, dyr;
  Value = 0;
  Norm = 0;
  for (int y = y0; y <= y1; y++)
  {
    dyr = yl - (y+0.5f);
    if (dyr < 0) dyr *= -1;
    LineValue = 0;
    LineNorm = 0;
    for (int x = x0; x <= x1; x++)
    {
      dxr = xl - (x+0.5f);
      if (dxr < 0) dxr *= -1;
      LineValue += map[y*width+x] * dxr;
      LineNorm += dxr;
    }
    Value += LineValue * dyr;
    Norm += dyr * LineNorm;
  }
  if (Norm == 0)
  {
    Value = 0;
    return (T)Value;
  }
  return (T)(Value/Norm);
}
template<class T > T imZeroOrderInterpolation (int width, int height, T * map, float xl, float yl) [inline]
Does Zero Order Interpolation (Nearest Neighborhood).
References imRound().
{
  int x0 = imRound(xl-0.5f);
  int y0 = imRound(yl-0.5f);
  x0 = x0<0? 0: x0>width-1? width-1: x0;
  y0 = y0<0? 0: y0>height-1? height-1: y0;
  return map[y0*width + x0];
}
template<class T > T imBilinearInterpolation (int width, int height, T * map, float xl, float yl) [inline]
Does Bilinear Interpolation.
{
  int x0, y0, x1, y1;
  float t, u;
  if (xl < 0.5)
  {
    x1 = x0 = 0;
    t = 0;
  }
  else if (xl >= width-0.5)
  {
    x1 = x0 = width-1;
    t = 0;
  }
  else
  {
    x0 = (int)(xl-0.5f);
    x1 = x0+1;
    t = xl - (x0+0.5f);
  }
  if (yl < 0.5)
  {
    y1 = y0 = 0;
    u = 0;
  }
  else if (yl >= height-0.5)
  {
    y1 = y0 = height-1;
    u = 0;
  }
  else
  {
    y0 = (int)(yl-0.5f);
    y1 = y0+1;
    u = yl - (y0+0.5f);
  }
  T fll = map[y0*width + x0];
  T fhl = map[y0*width + x1];
  T flh = map[y1*width + x0];
  T fhh = map[y1*width + x1];
  return (T)((fhh - flh - fhl + fll) * u * t +
                         (fhl - fll) * t +
                         (flh - fll) * u +
                                fll);
}
template<class T , class TU > T imBicubicInterpolation (int width, int height, T * map, float xl, float yl, TU Dummy) [inline]
Does Bicubic Interpolation.
{
  int X[4], Y[4];
  float t, u;
  (void)Dummy;
  if (xl >= width-0.5)
  {
    X[3] = X[2] = X[1] = width-1;
    X[0] = X[1]-1;
    t = 0;
  }
  else
  {
    X[1] = (int)(xl-0.5f);
    if (X[1] < 0) X[1] = 0;
    X[0] = X[1]-1;
    X[2] = X[1]+1;
    X[3] = X[1]+2;
    if (X[0] < 0) X[0] = 0;
    if (X[3] > width-1) X[3] = width-1;
    t = xl - (X[1]+0.5f);
  }
  if (yl >= height-0.5)
  {
    Y[3] = Y[2] = Y[1] = height-1;
    Y[0] = Y[1]-1;
    u = 0;
  }
  else
  {
    Y[1] = (int)(yl-0.5f);
    if (Y[1] < 0) Y[1] = 0;
    Y[0] = Y[1]-1;
    Y[2] = Y[1]+1;
    Y[3] = Y[1]+2;
    if (Y[0] < 0) Y[0] = 0;
    if (Y[3] > height-1) Y[3] = height-1;
    u = yl - (Y[1]+0.5f);
  }
  float CX[4], CY[4];
  // Optimize calculations
  {
    float c, c2, c3;
#define C0 (-c3 + 2.0f*c2 - c)
#define C1 (c3 - 2.0f*c2 + 1.0f)
#define C2 (-c3 + c2 + c)
#define C3 (c3 - c2)
    c = t;
    c2 = c*c; c3 = c2*c;
    CX[0] = C0; CX[1] = C1; CX[2] = C2; CX[3] = C3;
    c = u;
    c2 = c*c; c3 = c2*c;
    CY[0] = C0; CY[1] = C1; CY[2] = C2; CY[3] = C3;
#undef C0
#undef C1
#undef C2
#undef C3
  }
  TU LineValue, Value;
  float LineNorm, Norm;
  Value = 0;
  Norm = 0;
  for (int y = 0; y < 4; y++)
  {
    LineValue = 0;
    LineNorm = 0;
    for (int x = 0; x < 4; x++)
    {
      LineValue += map[Y[y]*width+X[x]] * CX[x];
      LineNorm += CX[x];
    }
    Value += LineValue * CY[y];
    Norm += CY[y] * LineNorm;
  }
  if (Norm == 0)
  {
    Value = 0;
    return (T)Value;
  }
  Value = (Value/Norm);
  int size = sizeof(T);
  if (size == 1)
    return (T)(Value<=(TU)0? (TU)0: Value<=(TU)255? Value: (TU)255);
  else
    return (T)(Value);
}
template<class T > void imMinMax (const T * map, int count, T & min, T & max, int abssolute = 0) [inline]
Calculates minimum and maximum values.
Referenced by imMinMaxType().
{
  if (abssolute)
    min = imAbs(map[0]);
  else
    min = map[0];
  max = min;
  for (int i = 1; i < count; i++)
  {
    T value;
    if (abssolute)
      value = imAbs(map[i]);
    else
      value = map[i];
    if (value > max)
      max = value;
    else if (value < min)
      min = value;
  }
}
template<class T > void imMinMaxType (const T * map, int count, T & min, T & max, int abssolute = 0) [inline]
Calculates minimum and maximum values with addtional considerations for data type conversion and normalized operations.
References imMinMax().
{
  int size_of = sizeof(imbyte);
  if (sizeof(T) == size_of)
  {
    /* for imbyte is always the maximum interval */
    min = 0;
    max = 255;
  }
  else
  {
    imMinMax(map, count, min, max, abssolute);
    /* if equal define a minimum interval */
    if (min == max)
    {
      max = min + 1;
      if (min != 0)
        min = min - 1;
    }
  }
}