IM: Color Manipulation
Color Manipulation
[Utilities]
Modules
HSI Color Coordinate System Conversions
Functions
float imColorZeroShift (int data_type)
int imColorMax (int data_type)
int imColorMin (int data_type)
template<class T >
T imColorQuantize (const float &value, const T &min, const T &max)
template<class T >
float imColorReconstruct (const T &value, const T &min, const T &max)
template<class T >
void imColorYCbCr2RGB (const T Y, const T Cb, const T Cr, T &R, T &G, T &B, const T &zero, const T &min, const T &max)
template<class T >
void imColorRGB2YCbCr (const T R, const T G, const T B, T &Y, T &Cb, T &Cr, const T &zero)
template<class T >
void imColorCMYK2RGB (const T C, const T M, const T Y, const T K, T &R, T &G, T &B, const T &max)
template<class T >
void imColorXYZ2RGB (const T X, const T Y, const T Z, T &R, T &G, T &B)
template<class T >
void imColorRGB2XYZ (const T R, const T G, const T B, T &X, T &Y, T &Z)
void imColorXYZ2Lab (const float X, const float Y, const float Z, float &L, float &a, float &b)
void imColorLab2XYZ (const float L, const float a, const float b, float &X, float &Y, float &Z)
void imColorXYZ2Luv (const float X, const float Y, const float Z, float &L, float &u, float &v)
void imColorLuv2XYZ (const float L, const float u, const float v, float &X, float &Y, float &Z)
float imColorTransfer2Linear (const float &nonlinear_value)
float imColorTransfer2Nonlinear (const float &value)
void imColorRGB2RGBNonlinear (const float RL, const float GL, const float BL, float &R, float &G, float &B)
template<class T >
T imColorRGB2Luma (const T R, const T G, const T B)
float imColorLuminance2Lightness (const float &Y)
float imColorLightness2Luminance (const float &L)
Detailed Description
Functions to convert from one color space to another, and color gammut utilities.
See im_color.h
Some Color Science
Y is luminance, a linear-light quantity. It is directly proportional to physical intensity weighted by the spectral sensitivity of human vision.
L* is lightness, a nonlinear luminance that aproximates the perception of brightness. It is nearly perceptual uniform. It has a range of 0 to 100.
Y' is luma, a nonlinear luminance that aproximates lightness.
Brightness is a visual sensation according to which an area apears to exhibit more or less light. It is a subjective quantity and can not be measured.
One unit of euclidian distante in CIE L*u*v* or CIE L*a*b* corresponds roughly to a just-noticeable difference (JND) of color.
 ChromaUV = sqrt(u*u + v*v)
 HueUV = atan2(v, u)
 SaturationUV = ChromaUV / L      (called psychometric saturation)
 (the same can be calculated for Lab)
IEC 61966-2.1 Default RGB colour space - sRGB
ITU-R Recommendation BT.709 (D65 white point).
D65 White Point (X,Y,Z) = (0.9505 1.0000 1.0890)
Documentation extracted from Charles Poynton - Digital Video and HDTV - Morgan Kaufmann - 2003.
Links
www.color.org - ICC
www.srgb.com - sRGB
www.poynton.com - Charles Poynton
www.littlecms.com - A free Color Management System (use this if you need precise color conversions)
Color Component Intervals
When minimum and maximum values must be pre-defined values, the following values are used:
 byte   [0,255]              (1 byte)
 short  [-32768,32767]       (2 bytes)
 ushort [0,65535]            (2 bytes)
 int    [-8388608,+8388607]  (3 bytes of 4 possible)
 float  [0,1]                (4 bytes)
Usually this intervals are used when converting from real to integer, and when demoting an integer data type.
Function Documentation
float imColorZeroShift (int data_type) [inline]
Returns the zero value for YCbCr color conversion.
When data type is unsigned Cb and Cr are shifted to 0-max. So before they can be used in conversion equations Cb and Cr values must be shifted back to fix the zero position.
{
  float zero[] = {128.0f,     // [-128,+127]
                  0,
                  32768.0f,   // [-32768,+32767]
                  0,
                  0,
                  0};
  return zero[data_type];
}
int imColorMax (int data_type) [inline]
Returns the maximum value for pre-defined color conversion porpouses.
See Color Component Intervals.
{
  int max[] = {255,
               32767,
               65535,
               8388607,
               1,
               0};
  return max[data_type];
}
int imColorMin (int data_type) [inline]
Returns the minimum value for pre-defined color conversion porpouses.
See Color Component Intervals.
{
  int min[] = {0,
               -32768,
               0,
               -8388608,
               0,
               0};
  return min[data_type];
}
template<class T > T imColorQuantize (const float & value, const T & min, const T & max) [inline]
Quantize 0-1 values into min-max.
Value are usually integers, but the dummy quantizer uses real values. See also Math Utilities.
References imRound().
{
  if (max == 1) return (T)value; // to allow a dummy quantizer
  if (value >= 1) return max;
  if (value <= 0) return min;
  float range = (float)max - (float)min + 1.0f;
  return (T)imRound(value*range - 0.5f) + min;
}
template<class T > float imColorReconstruct (const T & value, const T & min, const T & max) [inline]
Reconstruct min-max values into 0-1.
Values are usually integers, but the dummy reconstructor uses real values. See also Math Utilities.
{
  if (max == 1) return (float)value;  // to allow a dummy reconstructor
  if (value <= min) return 0;
  if (value >= max) return 1;
  float range = (float)max - (float)min + 1.0f;
  return (((float)value - (float)min + 0.5f)/range);
}
template<class T > void imColorYCbCr2RGB (const T Y, const T Cb, const T Cr, T & R, T & G, T & B, const T & zero, const T & min, const T & max) [inline]
Converts Y'CbCr to R'G'B' (all nonlinear).
ITU-R Recommendation 601-1 with no headroom/footroom.
 0 <= Y <= 1 ; -0.5 <= CbCr <= 0.5 ; 0 <= RGB <= 1
 R'= Y' + 0.000 *Cb + 1.402 *Cr
 G'= Y' - 0.344 *Cb - 0.714 *Cr
 B'= Y' + 1.772 *Cb + 0.000 *Cr
{
  float r = float(Y                        + 1.402f * (Cr - zero));
  float g = float(Y - 0.344f * (Cb - zero) - 0.714f * (Cr - zero));
  float b = float(Y + 1.772f * (Cb - zero));
  // now we should enforce min <= rgb <= max
  R = (T)IM_CROPMINMAX(r, min, max);
  G = (T)IM_CROPMINMAX(g, min, max);
  B = (T)IM_CROPMINMAX(b, min, max);
}
template<class T > void imColorRGB2YCbCr (const T R, const T G, const T B, T & Y, T & Cb, T & Cr, const T & zero) [inline]
Converts R'G'B' to Y'CbCr (all nonlinear).
ITU-R Recommendation 601-1 with no headroom/footroom.
 0 <= Y <= 1 ; -0.5 <= CbCr <= 0.5 ; 0 <= RGB <= 1
 Y' =  0.299 *R' + 0.587 *G' + 0.114 *B'
 Cb = -0.169 *R' - 0.331 *G' + 0.500 *B'
 Cr =  0.500 *R' - 0.419 *G' - 0.081 *B'
{
  Y  = (T)( 0.299f *R + 0.587f *G + 0.114f *B);
  Cb = (T)(-0.169f *R - 0.331f *G + 0.500f *B + (float)zero);
  Cr = (T)( 0.500f *R - 0.419f *G - 0.081f *B + (float)zero);
}
template<class T > void imColorCMYK2RGB (const T C, const T M, const T Y, const T K, T & R, T & G, T & B, const T & max) [inline]
Converts C'M'Y'K' to R'G'B' (all nonlinear).
This is a poor conversion that works for a simple visualization.
  0 <= CMYK <= 1 ; 0 <= RGB <= 1
  R = (1 - K) * (1 - C)
  G = (1 - K) * (1 - M)
  B = (1 - K) * (1 - Y)
{
  T W = max - K;
  R = (T)((W * (max - C)) / max);
  G = (T)((W * (max - M)) / max);
  B = (T)((W * (max - Y)) / max);
}
template<class T > void imColorXYZ2RGB (const T X, const T Y, const T Z, T & R, T & G, T & B) [inline]
Converts CIE XYZ to Rec 709 RGB (all linear).
ITU-R Recommendation BT.709 (D65 white point).
  0 <= XYZ <= 1 ; 0 <= RGB <= 1
  R =  3.2406 *X - 1.5372 *Y - 0.4986 *Z
  G = -0.9689 *X + 1.8758 *Y + 0.0415 *Z
  B =  0.0557 *X - 0.2040 *Y + 1.0570 *Z
{
  float r =  3.2406f *X - 1.5372f *Y - 0.4986f *Z;
  float g = -0.9689f *X + 1.8758f *Y + 0.0415f *Z;
  float b =  0.0557f *X - 0.2040f *Y + 1.0570f *Z;
  // we need to crop because not all XYZ colors are visible
  R = (T)IM_FLOATCROP(r);
  G = (T)IM_FLOATCROP(g);
  B = (T)IM_FLOATCROP(b);
}
template<class T > void imColorRGB2XYZ (const T R, const T G, const T B, T & X, T & Y, T & Z) [inline]
Converts Rec 709 RGB to CIE XYZ (all linear).
ITU-R Recommendation BT.709 (D65 white point).
  0 <= XYZ <= 1 ; 0 <= RGB <= 1
  X = 0.4124 *R + 0.3576 *G + 0.1805 *B
  Y = 0.2126 *R + 0.7152 *G + 0.0722 *B
  Z = 0.0193 *R + 0.1192 *G + 0.9505 *B
{
  X = (T)(0.4124f *R + 0.3576f *G + 0.1805f *B);
  Y = (T)(0.2126f *R + 0.7152f *G + 0.0722f *B);
  Z = (T)(0.0193f *R + 0.1192f *G + 0.9505f *B);
}
void imColorXYZ2Lab (const float X, const float Y, const float Z, float & L, float & a, float & b) [inline]
Converts CIE XYZ (linear) to CIE L*a*b* (nonlinear).
The white point is D65.
  0 <= L <= 1 ; -0.5 <= ab <= +0.5 ; 0 <= XYZ <= 1
  if (t > 0.008856)
    f(t) = pow(t, 1/3)
  else
    f(t) = 7.787*t + 16/116
  fX = f(X / Xn)      fY = f(Y / Yn)      fZ = f(Z / Zn)
  L = 1.16 * fY - 0.16
  a = 2.5 * (fX - fY)
  b = (fY - fZ)
{
  float fX = X / 0.9505f;  // white point D65
  float fY = Y / 1.0f;
  float fZ = Z / 1.0890f;
  fX = IM_FWLAB(fX);
  fY = IM_FWLAB(fY);
  fZ = IM_FWLAB(fZ);
  L = 1.16f * fY - 0.16f;
  a = 2.5f * (fX - fY);
  b = (fY - fZ);
}
void imColorLab2XYZ (const float L, const float a, const float b, float & X, float & Y, float & Z) [inline]
Converts CIE L*a*b* (nonlinear) to CIE XYZ (linear).
The white point is D65.
0 <= L <= 1 ; -0.5 <= ab <= +0.5 ; 0 <= XYZ <= 1
{
  float fY = (L + 0.16f) / 1.16f;
  float gY = IM_GWLAB(fY);
  float fgY = IM_FWLAB(gY);
  float gX = fgY + a / 2.5f;
  float gZ = fgY - b;
  gX = IM_GWLAB(gX);
  gZ = IM_GWLAB(gZ);
  X = gX * 0.9505f;     // white point D65
  Y = gY * 1.0f;
  Z = gZ * 1.0890f;
}
void imColorXYZ2Luv (const float X, const float Y, const float Z, float & L, float & u, float & v) [inline]
Converts CIE XYZ (linear) to CIE L*u*v* (nonlinear).
The white point is D65.
  0 <= L <= 1 ; -1 <= uv <= +1 ; 0 <= XYZ <= 1
  Y = Y / 1.0      (for D65)
  if (Y > 0.008856)
    fY = pow(Y, 1/3)
  else
    fY = 7.787 * Y + 0.16/1.16
  L = 1.16 * fY - 0.16
  U(x, y, z) = (4 * x)/(x + 15 * y + 3 * z)
  V(x, y, z) = (9 * x)/(x + 15 * y + 3 * z)
  un = U(Xn, Yn, Zn) = 0.1978      (for D65)
  vn = V(Xn, Yn, Zn) = 0.4683      (for D65)
  fu = U(X, Y, Z)
  fv = V(X, Y, Z)
  u = 13 * L * (fu - un)
  v = 13 * L * (fv - vn)
{
  float XYZ = (float)(X + 15 * Y + 3 * Z);
  float fY = Y / 1.0f;
  if (XYZ != 0)
  {
    L = 1.16f * IM_FWLAB(fY) - 0.16f;
    u = 6.5f * L * ((4 * X)/XYZ - 0.1978f);
    v = 6.5f * L * ((9 * Y)/XYZ - 0.4683f);
  }
  else
  {
    L = u = v = 0;
  }
}
void imColorLuv2XYZ (const float L, const float u, const float v, float & X, float & Y, float & Z) [inline]
Converts CIE L*u*v* (nonlinear) to CIE XYZ (linear).
The white point is D65. 0 <= L <= 1 ; -0.5 <= uv <= +0.5 ; 0 <= XYZ <= 1
{
  float fY = (L + 0.16f) / 1.16f;
  Y = IM_GWLAB(fY) * 1.0f;
  float ul = 0.1978f, vl = 0.4683f;
  if (L != 0)
  {
    ul = u / (6.5f * L) + 0.1978f;
    vl = v / (6.5f * L) + 0.4683f;
  }
  X = ((9 * ul) / (4 * vl)) * Y;
  Z = ((12 - 3 * ul - 20 * vl) / (4 * vl)) * Y;
}
float imColorTransfer2Linear (const float & nonlinear_value) [inline]
Converts nonlinear values to linear values.
We use the sRGB transfer function. sRGB uses ITU-R 709 primaries and D65 white point.
  0 <= l <= 1 ; 0 <= v <= 1
  if (v < 0.03928)
    l = v / 12.92
  else
    l = pow((v + 0.055) / 1.055, 2.4)
{
  if (nonlinear_value < 0.03928f)
    return nonlinear_value / 12.92f;
  else
    return powf((nonlinear_value + 0.055f) / 1.055f, 2.4f);
}
float imColorTransfer2Nonlinear (const float & value) [inline]
Converts linear values to nonlinear values.
We use the sRGB transfer function. sRGB uses ITU-R 709 primaries and D65 white point.
  0 <= l <= 1 ; 0 <= v <= 1
  if (l < 0.0031308)
    v = 12.92 * l
  else
    v = 1.055 * pow(l, 1/2.4) - 0.055
Referenced by imColorRGB2RGBNonlinear().
{
  if (value < 0.0031308f)
    return 12.92f * value;
  else
    return 1.055f * powf(value, 1.0f/2.4f) - 0.055f;
}
void imColorRGB2RGBNonlinear (const float RL, const float GL, const float BL, float & R, float & G, float & B) [inline]
Converts RGB (linear) to R'G'B' (nonlinear).
References imColorTransfer2Nonlinear().
{
  R = imColorTransfer2Nonlinear(RL);
  G = imColorTransfer2Nonlinear(GL);
  B = imColorTransfer2Nonlinear(BL);
}
template<class T > T imColorRGB2Luma (const T R, const T G, const T B) [inline]
Converts R'G'B' to Y' (all nonlinear).
 Y'  =  0.299 *R' + 0.587 *G' + 0.114 *B'
{
  return (T)((299 * R + 587 * G + 114 * B) / 1000);
}
float imColorLuminance2Lightness (const float & Y) [inline]
Converts Luminance (CIE Y) to Lightness (CIE L*) (all linear).
The white point is D65.
  0 <= Y <= 1 ; 0 <= L* <= 1
  Y = Y / 1.0      (for D65)
  if (Y > 0.008856)
    fY = pow(Y, 1/3)
  else
    fY = 7.787 * Y + 0.16/1.16
  L = 1.16 * fY - 0.16
{
  return 1.16f * IM_FWLAB(Y) - 0.16f;
}
float imColorLightness2Luminance (const float & L) [inline]
Converts Lightness (CIE L*) to Luminance (CIE Y) (all linear).
The white point is D65.
  0 <= Y <= 1 ; 0 <= L* <= 1
  fY = (L + 0.16)/1.16
  if (fY > 0.20689)
    Y = pow(fY, 3)
  else
    Y = 0.1284 * (fY - 0.16/1.16)
  Y = Y * 1.0      (for D65)
{
  float fY = (L + 0.16f) / 1.16f;
  return IM_GWLAB(fY);
}